AIDL: golden tests
Let it be stated for the record, that I really don't like golden tests.
Well, more than that, golden tests are no alternative to real testing.
Luckily, in AIDL, we have a huge amount of other tests. However, there
is an argument for keeping golden tests so that we can see easily what
compiler changes change our output.

Overview:
- existing golden tests require manually editing C++ strings. Here, we
  diff the entire output (including things like 'timestamp' files and
  '.d' files) which either weren't tested before or required additional
  setup. Here, the aidl_interface build is integration testing, and we
  don't have to worry about additional files.
- we now test every backend (not just some small subset).
- we run tests w/ certain options enabled (logging)
- this is made part of the build (can't miss it). The script is actually
  really quick to run, but we could add an easy way to skip it for
  active development.
- (critically) updating the files is done with a single command (no more
  manually editing C++ file strings in multiple places, just accept the
  diffs). That also means no more avoiding improvements to
  auto-generated code, just because of these golden file diffs.

Caveats:
- We're testing a different set of interface outputs now, maybe more
  than we need to be (whatever - we are also testing more in some
  sense)
- The list of files to check are duplicated in Android.bp srcs and in
  the script (not ideal, but commented)
- This isn't using the test system's 'data' attribute to package these
  files in separate tests. Quite frankly though, this is lower level
  infrastructure, and the test (diff) is trivial in time to run. Since
  we are directly requiring source files here, I expect this will
  interact well with RBE.

Fixes: 175911955
Test: the following build output produced, when these files change

diff -r
./out/soong/.intermediates/system/tools/aidl/aidl_test_loggable_interface-ndk_platform-source/gen/include/aidl/android/aidl/loggable/Union.h
./system/tools/aidl/tests/golden_output/aidl_test_loggable_int
erface-ndk_platform-source/gen/include/aidl/android/aidl/loggable/Union.h
30a31
>   // some no-longer generated comment
ERROR: The AIDL compiler is outputting files in an unknown way.
ERROR: to accept these changes, please run:
ERROR:     $ANDROID_BUILD_TOP/system/tools/aidl/tests/golden_test.sh
update
sbox command failed with err:
out/soong/.temp/sbox/931871b05bb255111d695cee2541f9d9ded3c5ed/tools/out/bin/aidl-golden-test
check && echo 'int main(){return 0;}' >
out/soong/.temp/sbox/931871b05bb255111d695cee2541f9d9ded3c5ed/out/TODO_b_37575
883.cpp
exit status 1

Change-Id: Ic293ac09849f1cead3aa46bfe431964b6804e2df