ShallowIntegralCopy: report user errors w/o crash
Needs to check that ValueString returns non-empty string.
Bug: 145066992
Test: aidl_parser_fuzzer with:
    "enum F{s=2e8,z}"

Needs to consider unsuccessful evaluate as user error not as AIDL_FATAL
(also removed confusing print out of 'type' since in the case where it
fails to evaluate, it may be something like 'binary expression').
Fixes: 145011986
Test: aidl_parser_fuzzer with:
    "enum i{Uecp,a333333=033-3.33333372928 ,ut,}"
ERROR: a/path/Foo.aidl:1.35-38: Failed to parse expression as integer: 033-3.33333372928

Change-Id: If76948afd96e7f975b6f834b59f9e29db7205cd0