Compile NDK backend against different versions.
Note - this doesn't catch errors related to __builtin_available
because it always appears to work in platform builds.

Bug: 219987524
Test: introduce error and get nice error message:
/aosp/frameworks/native/libs/binder/ndk/include_cpp/android/binder_interface_utils.h:72:9: error: 'AIBinder_Class_setHandleShellCommand' is only available on Android 30 or newer [clang-diagnostic-unguarded-availability]
        AIBinder_Class_setHandleShellCommand(nullptr, nullptr);

Change-Id: Ib9508889ef1fb21cf3edee0d2724a2169288e1f1